apiVersion: v1
kind: ConfigMap
metadata:
  name: dl-app-config
  namespace: dl-clinical-app
  labels:
    app.kubernetes.io/name: dl-app-config
data:
  BACKEND_API_URL: "http://backend-svc:5000"
  PORT: "5000"
  STREAMLIT_SERVER_PORT: "8501"
  ENVIRONMENT: "kubernetes-cluster"
