apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: dl-clinical-app
  labels:
    app: dl-frontend
    tier: ui
spec:
  type: NodePort
  selector:
    app: dl-frontend
    tier: ui
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30001
    protocol: TCP
    name: http-ui
