apiVersion: v1
kind: Service
metadata:
  name: dl-backend-svc
  namespace: dl-production-app
  labels:
    app: dl-backend
    tier: api
    app.kubernetes.io/name: dl-backend
    app.kubernetes.io/part-of: dl-clinical-suite
    task: "13"
spec:
  type: NodePort
  selector:
    app: dl-backend
    tier: api
  ports:
  - name: http-api
    port: 5000
    targetPort: 5000
    nodePort: 30500
    protocol: TCP
