services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME:-myuser}/dl-clinical-backend:v1.0
    container_name: dl_clinical_backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - clinical_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME:-myuser}/dl-clinical-frontend:v1.0
    container_name: dl_clinical_frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - clinical_net

networks:
  clinical_net:
    driver: bridge
