apiVersion: v1
kind: Service
metadata:
  name: dl-frontend-svc
  namespace: dl-production-app
  labels:
    app: dl-frontend
    tier: frontend
spec:
  type: NodePort
  selector:
    app: dl-frontend
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      nodePort: 31501
      protocol: TCP
