apiVersion: v1
kind: Service
metadata:
  name: dl-frontend-svc
  namespace: dl-production-app
  labels:
    app: dl-frontend
    task: "14"
spec:
  type: NodePort
  selector:
    app: dl-frontend
    tier: ui
  ports:
  - name: http-ui
    port: 8501
    targetPort: 8501
    nodePort: 31501
    protocol: TCP
